baseUrl = "https://Rucch.github.io/2015"
languageCode = "en-us"
title = "Power Guide"
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

canonifyurls = true


[taxonomies]
menu = "menu"
group = "groups"
